### ISSUE TITLE
STM32F030C6 incorrect RAM parameter in linker file

### ISSUE THREAD

**Issue by fabianhugo** [microsoft/pxt-arcade-smart-shield#5]
when compiling and debugging the main branch of this repository for an STM32F030C6 target (workflow described in: [issue 4](https://github.com/microsoft/pxt-arcade-smart-shield/issues/4) , the debugger does not halt as expected at the main() function of the program, and the firmware does not react as expected (display stays dark). When I ask the debugger to halt, the program counter reads 0xfffffffe, so probably at some kind of error handler.

The linker file in targets/f030: linker.ld reveals in line: 
/* Specify the memory areas */
MEMORY
{
RAM (xrw)      : ORIGIN = 0x20000000, LENGTH = 6K
FLASH (rx)      : ORIGIN = 0x8000000, LENGTH = 32K
}
that a RAM of 6K is used, while the actual STM32F030C6 microcontroller only has 4K ram. Changing this parameter to 4K throws the error:  region `RAM' overflowed by 352 bytes ****

I replaced the config, linker and startup files in the targets folder with the ones generated for STM32F030C6 by CubeIDE, and now the project compiles, and the debugger starts in the main() function. Attached are the linker files that I use:  [linker_files.zip](https://github.com/user-attachments/files/17705483/linker.zip)
With this change my display also turns on its backlight correctly. Unfortunately, displaying the test screen still does not work. Either a hardware issue or the firmware still does not work properly. My schematic is the following, I use the ILI9341 bare screen from LCSC.
![Image](https://github.com/user-attachments/assets/460787d8-75f3-4210-b31e-7f2ae19d3f2f)

Any hints very welcome

**Comment by tballmsft** [comment]
I believe this is fixed by: https://github.com/microsoft/pxt-arcade-smart-shield/commit/9e3dc8092fb7fe12fc06b6ae6d0a948c8b88345c

**Comment by fabianhugo** [comment]
thanks and happy new year. yes that fixed the problem with the debugger. I still have the problem with the empty backlit screen, so that is probably a layout or screen issue.
